data_path: ./all_10_species/
dataframe_csv: better.csv
duration_col: DURATION
early_stopping: false
epochs: 10
file_name_col: FILE NAME
freq_mask_p: 0.5
freq_mask_param: 10
git_hash: d187ead6c93b3fe9c85709a25a94eaaacbfcdf75
hop_length: 512
imbalance_sampler: false
jobs: 2
learning_rate: 0.001
logging: true
logging_freq: 20
manual_id_col: MANUAL ID
map_debug: false
max_time: 5
min_valid_map_delta: 0.01
mixed_precision: true
mixup_p: 0
model: eca_nfnet_l0
model_checkpoint: ''
n_fft: 1400
n_mels: 194
noise_p: 0.35
noise_std: 0.005
num_fold: 5
offset_col: OFFSET
patience: 3
pos_weight: 1
sample_rate: 32000
seed: 0
smoothing: 0.05
time_mask_p: 0.5
time_mask_param: 25
time_shift_p: 0
train_batch_size: 4
train_test_split: 0.8
valid_freq: 2000
validation_batch_size: 4
verbose: false
