name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: asid
        environment-file: environment.yml
        auto-activate-base: false

    - name: check
      run: |
        conda info
    # - name: add conda to bash
    #   run: |
    #     conda init bash 
    # - name: config env to asid
    #   run: |
    #     conda activate asid
    # - name: check
    #   run: |
    #     conda info
    - name: install pylint
      run: |
        conda install pylint
        conda run pip install pylint
        conda list
    - name: Check env params
      run: |
        conda info --envs 
        conda info
    - run: |
        conda run python3 -m pylint $(git ls-files '*.py') --rcfile=.pylintrc
