name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - name: Checkout
        uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        #activate-environment: asid
        #environment-file: environment.yml
        auto-activate-base: false
    - run: |
        pwd
        ls
        ls -a
        ls-files
        # conda info
        # conda list
        # conda install pylint
        # pylint $(git ls-files '*.py') --rcfile=.pylintrc
