name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Conda and activate env
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml
        $CONDA/bin/conda init bash
        $CONDA/bin/conda activate asid
    - name: install pylint
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda install pylint
    - name: Analysing the code with pylint
      run: |
        $CONDA/bin/pylint $(git ls-files '*.py') --rcfile=.pylintrc
